import { NextResponse } from 'next/server';
import { prisma } from '../../../lib/prisma';
import { currentUser } from '../../../lib/auth';
export async function GET(request:Request){
 try{const user=await currentUser();if(!user)return NextResponse.json({ok:false,error:'请先登录'},{status:401});const classId=new URL(request.url).searchParams.get('classroomId');if(user.role==='TEACHER'&&classId){const m=await prisma.classMember.findUnique({where:{classroomId_userId:{classroomId:classId,userId:user.id}}});if(!m)return NextResponse.json({ok:false,error:'无权查看该班级'},{status:403})}const where=user.role==='TEACHER'?(classId?{classroomId:classId}:{}):{studentId:user.id};const records=await prisma.simulationRecord.findMany({where,orderBy:{createdAt:'desc'},take:200});const revised=records.filter(x=>x.status==='REVISED').length;const byScenario:Record<string,{title:string,total:number,revised:number,score:number}>={};for(const x of records){const k=x.scenarioId;byScenario[k]??={title:x.scenarioTitle,total:0,revised:0,score:0};byScenario[k].total++;byScenario[k].score+=x.score;if(x.status==='REVISED')byScenario[k].revised++}const students=await prisma.classMember.count({where:classId?{classroomId:classId,memberRole:'STUDENT'}:{memberRole:'STUDENT'}});return NextResponse.json({ok:true,records,stats:{students,total:records.length,revised,revisionRate:records.length?Math.round(revised/records.length*100):0,byScenario}})}catch{return NextResponse.json({ok:false,error:'数据库读取失败'},{status:500})}
}
export async function POST(request:Request){
 try{const b=await request.json();const student=await currentUser();if(!student||student.role!=='STUDENT')return NextResponse.json({ok:false,error:'仅学生可提交'},{status:403});const membership=await prisma.classMember.findFirst({where:{userId:student.id,memberRole:'STUDENT'},include:{classroom:{include:{cycles:{orderBy:{startsAt:'desc'},take:1}}}}});if(!membership)return NextResponse.json({ok:false,error:'请先加入班级'},{status:400});const cycle=membership.classroom.cycles[0];const record=await prisma.simulationRecord.create({data:{studentId:student.id,classroomId:membership.classroomId,cycleId:cycle?.id,scenarioId:b.scenarioId,scenarioTitle:b.scenarioTitle,stepIndex:b.stepIndex,relationsJson:JSON.stringify(b.relations||[]),elementsJson:JSON.stringify(b.elements||{}),firstChoice:b.firstChoice,firstReason:b.firstReason,status:'SUBMITTED',score:typeof b.score==='number'?b.score:60}});if(['platform','secondhand'].includes(b.scenarioId)){await prisma.teacherReview.create({data:{app:'PAYMENT_SIMULATOR',reviewType:'OPEN_SCENARIO',title:`${b.scenarioTitle}主体与结算判断`,detail:'多主体平台场景需要教师结合交易条件复核。',targetId:record.id,studentLabel:student.displayName}})}return NextResponse.json({ok:true,record,classroom:membership.classroom.name,cycle:cycle?.name})}catch{return NextResponse.json({ok:false,error:'推演保存失败'},{status:500})}
}
export async function PATCH(request:Request){
 try{const b=await request.json();const user=await currentUser();if(!user)return NextResponse.json({ok:false,error:'请先登录'},{status:401});const existing=await prisma.simulationRecord.findUnique({where:{id:b.id}});if(!existing||(user.role!=='TEACHER'&&existing.studentId!==user.id))return NextResponse.json({ok:false,error:'无权修改'},{status:403});const record=await prisma.simulationRecord.update({where:{id:b.id},data:{revisedJson:JSON.stringify(b.revised||{}),status:'REVISED',score:typeof b.score==='number'?b.score:88}});return NextResponse.json({ok:true,record})}catch{return NextResponse.json({ok:false,error:'订正保存失败'},{status:500})}
}
