'use client';
import {useEffect,useState} from 'react';
type Phase='judge'|'learn'|'improve'|'done';
const tasks=[{name:'把专业问题说清楚',why:'学会发现模糊任务缺少的必要信息，而不是盲目向AI追加无关内容。'},{name:'检查AI回答是否可靠',why:'AI回答得流畅，也可能只看资金收付，遗漏已经取得的商品、形成的义务和不同时间节点。'},{name:'保护学习与业务数据',why:'成绩数据有分析价值，但个人信息和机构数据不能未经处理直接交给公共AI工具。'}];
const needed=['使用“内容丰富、形式新颖、效果显著”等笼统要求，却没有说明评价标准','让AI自行假定活动时间、参加人数和经费','要求方案“越详细越好”，却没有说明方案的实际用途','没有说明最终需要活动流程、时间表、经费表还是宣传文案'];
const distractors=['明确活动面向全校学生','说明这是一项AI主题活动'];
const issues=['只根据银行卡是否扣款判断','忽视购买当天已经取得耳机','忽视购买当天形成还款义务','混淆购买和还款两个时间节点'];
export default function LiteracyLab(){
 const [user,setUser]=useState<any>(undefined),[username,setUsername]=useState('student_demo'),[password,setPassword]=useState('demo1234'),[loginError,setLoginError]=useState('');
 const [step,setStep]=useState(0),[phase,setPhase]=useState<Phase>('judge'),[completed,setCompleted]=useState<boolean[]>([false,false,false]),[first,setFirst]=useState<any[]>([{}, {}, {}]),[work,setWork]=useState<any[]>([{selected:[]},{decision:'',issues:[]},{plan:''}]),[improved,setImproved]=useState<any[]>([{audience:'',goal:'',limits:'',format:'',verify:''},{text:''},{choice:'',safeguards:[]}]),[saving,setSaving]=useState(false),[saveError,setSaveError]=useState('');
 useEffect(()=>{fetch('/api/auth/me').then(r=>r.json()).then(d=>setUser(d.ok?d.user:null)).catch(()=>setUser(null))},[]);
 async function login(){setLoginError('');const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password})}),d=await r.json();if(d.ok&&d.user.role==='STUDENT')setUser(d.user);else setLoginError(d.user?.role==='TEACHER'?'请使用学生账号进入训练':d.error||'登录失败')}
 function updateWork(x:any){setWork(v=>v.map((a,i)=>i===step?x:a))}function updateImproved(x:any){setImproved(v=>v.map((a,i)=>i===step?x:a))}
 function submitJudge(){setFirst(v=>v.map((a,i)=>i===step?JSON.parse(JSON.stringify(work[step])):a));setPhase('learn');document.querySelector('.literacy-lab')?.scrollIntoView({behavior:'smooth',block:'start'})}
 function firstScore(){if(step===0){const s=first[0].selected||[];return Math.round(needed.filter(x=>s.includes(x)).length/needed.length*80+Math.max(0,20-distractors.filter(x=>s.includes(x)).length*7))}if(step===1){return (first[1].decision==='判断不完整，需要找出问题并修改'?20:0)+(first[1].issues||[]).filter((x:string)=>issues.includes(x)).length*20}return first[2].plan==='方案C：删除姓名和学号，只保留匿名编号、成绩区间和题型正确率'?100:0}
 function diagnosis(){if(step===0){const s=first[0].selected||[];return [...needed.filter(x=>!s.includes(x)).map(x=>`尚未识别必要信息：${x}`),...distractors.filter(x=>s.includes(x)).map(x=>`加入了无关信息：${x}`)]}if(step===1)return [...(first[1].decision!=='核验后使用'?['尚未判断出这段说法不完整，需要进一步查找问题']:[]),...issues.filter(x=>!(first[1].issues||[]).includes(x)).map(x=>`尚未发现：${x}`)];return first[2].plan==='方案C：删除姓名和学号，只保留匿名编号、成绩区间和题型正确率'?[]:['原方案仍可能暴露个人信息，或没有遵循最小必要原则']}
 function canImprove(){if(step===0){const x=improved[0];return [x.audience,x.goal,x.limits,x.format,x.verify].every((v:string)=>v.trim().length>=5)}if(step===1)return improved[1].text==='购买当天已经取得耳机，并形成以后还款的义务；下月还款时银行卡资金减少，偿还义务随之减少。两个时间节点需要分别分析。';return improved[2].choice==='只使用匿名汇总数据'&&['删除姓名','删除完整学号','只保留分析所需数据'].every(x=>(improved[2].safeguards||[]).includes(x))}
 async function save(){setSaving(true);setSaveError('');const fs=firstScore(),tags=diagnosis();try{const r=await fetch('/api/literacy',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind:['structure','verify','privacy'][step],title:tasks[step].name,firstScore:fs,tags,firstAnswer:first[step],revisedAnswer:improved[step],revisedScore:100,revisionNote:'已依据方法反馈完成应用改进'})}),d=await r.json();if(!d.ok)throw new Error(d.error||'保存失败');setCompleted(v=>v.map((x,i)=>i===step?true:x));if(step===2){localStorage.setItem('finance-ai-prep-complete','true');window.dispatchEvent(new Event('finance-ai-prep-updated'))}setPhase('done')}catch(e:any){setSaveError(e.message)}finally{setSaving(false)}}
 function next(){if(step<2){setStep(step+1);setPhase(completed[step+1]?'done':'judge')}else setPhase('done')}
 if(user===undefined)return <div className="auth-loading">正在检查账号…</div>;
 if(!user||user.role!=='STUDENT')return <div className="hub-login"><h3>学生登录</h3><p>训练记录将写入本机SQLite，供教师查看匿名诊断。</p><label>账号<input value={username} onChange={e=>setUsername(e.target.value)}/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{loginError&&<em>{loginError}</em>}<button onClick={login}>登录并开始训练</button></div>;
 const fscore=phase==='judge'?0:firstScore(),tags=phase==='judge'?[]:diagnosis();
 return <div className="literacy-lab"><div className="logged-user">当前学生：{user.displayName}<span>记录保存至本机SQLite</span></div><div className="wizard-progress">{tasks.map((t,i)=><button key={t.name} className={`${i===step?'active':''} ${completed[i]?'complete':''}`} onClick={()=>{setStep(i);setPhase(completed[i]?'done':'judge')}}><i>{completed[i]?'✓':i+1}</i><span><b>{t.name}</b><small>{completed[i]?'已完成':i===step?'进行中':'未开始'}</small></span></button>)}</div><div className="why-box"><b>为什么学习这一项？</b><p>{tasks[step].why}</p></div>
 {step===0&&<>{phase==='judge'&&<section className="task-stage"><span>第一阶段 · 独立判断</span><h3>下面这份任务要求中，哪些做法会影响AI生成结果的可用性？</h3><p><b>多选题：</b>选择所有存在问题的做法。此时不显示答案。</p><div className="quote">请设计一项面向全校学生的AI主题活动，活动要内容丰富、形式新颖、效果显著。时间、人数和经费可以由AI根据常见情况自行确定，方案写得越详细越好。</div><div className="choice-cards">{[...needed,...distractors].map(x=><label className={(work[0].selected||[]).includes(x)?'picked':''} key={x}><input type="checkbox" checked={(work[0].selected||[]).includes(x)} onChange={e=>updateWork({selected:e.target.checked?[...(work[0].selected||[]),x]:(work[0].selected||[]).filter((y:string)=>y!==x)})}/>{x}</label>)}</div><button className="stage-submit" disabled={!(work[0].selected||[]).length} onClick={submitJudge}>提交第1项多选判断</button></section>}{phase==='learn'&&<Feedback score={fscore} tags={tags} onNext={()=>setPhase('improve')}/>} {phase==='improve'&&<section className="task-stage"><span>第三阶段 · 应用改进</span><h3>使用刚学到的方法，创建一项可执行的任务</h3><div className="creation-note"><b>任务创建，不设唯一答案</b><p>下面每栏单选1项。所有选项都可以成立，请组合出一项符合当前需要的活动任务。</p></div><div className="assemble-grid"><label>这次活动面向谁？<select value={improved[0].audience} onChange={e=>updateImproved({...improved[0],audience:e.target.value})}><option value="">请选择</option><option>高职一年级学生</option><option>毕业年级学生</option><option>全校学生</option></select></label><label>希望达到什么效果？<select value={improved[0].goal} onChange={e=>updateImproved({...improved[0],goal:e.target.value})}><option value="">请选择</option><option>学会检查AI回答是否可靠</option><option>认识AI使用风险</option><option>完成专业实践任务</option></select></label><label>活动条件是什么？<select value={improved[0].limits} onChange={e=>updateImproved({...improved[0],limits:e.target.value})}><option value="">请选择</option><option>90分钟、40人以内、普通教室</option><option>45分钟、20人以内、普通教室</option><option>2课时、一个完整班级</option></select></label><label>希望AI怎样呈现结果？<select value={improved[0].format} onChange={e=>updateImproved({...improved[0],format:e.target.value})}><option value="">请选择</option><option>形成完整活动方案</option><option>按表格呈现</option><option>列出分步骤清单</option></select></label><label>AI回答中哪些内容必须查证？<select value={improved[0].verify} onChange={e=>updateImproved({...improved[0],verify:e.target.value})}><option value="">请选择</option><option>政策名称、数据来源和专业结论</option><option>引用的案例和参考资料</option><option>所有涉及事实的内容</option></select></label></div><div className="assembled-preview"><b>系统自动拼装的任务</b><p>请面向【{improved[0].audience||'服务对象'}】设计一项活动，目标是【{improved[0].goal||'活动目标'}】，条件为【{improved[0].limits||'活动条件'}】。请【{improved[0].format||'呈现结果'}】，并对【{improved[0].verify||'需要查证的内容'}】标明来源并提示人工核验。</p></div><button className="stage-submit" disabled={!canImprove()||saving} onClick={save}>{saving?'正在保存':'保存第1项学习证据'}</button>{saveError&&<em className="save-error">{saveError}</em>}</section>}</>}
 {step===1&&<>{phase==='judge'&&<section className="task-stage"><span>第一阶段 · 独立判断</span><div className="quote"><b>以下是AI对花呗事项的分析：</b><br/>“使用花呗购买耳机时，银行卡没有立即扣款，所以购买当天没有发生需要分析的经济事项。等到下月银行卡还款时，再统一分析这笔业务。”</div><h3>先判断：这段说法是否完整、可靠？</h3><p><b>单选题：</b>请选择最符合你判断的一项。</p><div className="radio-row">{['判断完整，可以直接采用','判断不完整，需要找出问题并修改','不需要分析，直接删除'].map(x=><label className={work[1].decision===x?'picked':''} key={x}><input type="radio" checked={work[1].decision===x} onChange={()=>updateWork({...work[1],decision:x})}/>{x}</label>)}</div><h3>这段说法具体遗漏或混淆了什么？</h3><p><b>多选题：</b>选择所有存在的问题。</p><div className="choice-cards">{issues.map(x=><label className={(work[1].issues||[]).includes(x)?'picked':''} key={x}><input type="checkbox" checked={(work[1].issues||[]).includes(x)} onChange={e=>updateWork({...work[1],issues:e.target.checked?[...(work[1].issues||[]),x]:(work[1].issues||[]).filter((y:string)=>y!==x)})}/>{x}</label>)}</div><button className="stage-submit" disabled={!work[1].decision} onClick={submitJudge}>提交第2项独立判断</button></section>}{phase==='learn'&&<Feedback score={fscore} tags={tags} onNext={()=>setPhase('improve')} checklist={['是否只根据银行卡是否扣款进行判断？','购买当天是否已经取得耳机？','购买当天是否形成以后还款的义务？','购买和还款是否属于两个时间节点？']}/>} {phase==='improve'&&<section className="task-stage"><span>第三阶段 · 应用改进</span><h3>把原回答改成可以进入后续核验的版本</h3><div className="version-list">{['银行卡没有扣款，因此购买当天没有发生任何需要分析的事项。','购买当天已经取得耳机，并形成以后还款的义务；下月还款时银行卡资金减少，偿还义务随之减少。两个时间节点需要分别分析。','只需要记录下月银行卡还款，不需要分析购买当天发生了什么。'].map(x=><label className={improved[1].text===x?'picked':''} key={x}><input type="radio" checked={improved[1].text===x} onChange={()=>updateImproved({text:x})}/>{x}</label>)}</div><button className="stage-submit" disabled={!canImprove()||saving} onClick={save}>保存第2项学习证据</button>{saveError&&<em className="save-error">{saveError}</em>}</section>}</>}
 {step===2&&<>{phase==='judge'&&<section className="task-stage"><span>第一阶段 · 独立判断</span><h3>教师准备让公共AI分析班级成绩，原表含姓名、学号、成绩和切屏次数。应采用哪个方案？</h3><p><b>单选题：</b>选择一种最符合数据最小化原则的方案。</p><div className="plan-list">{['方案A：直接上传原始成绩表','方案B：删除姓名，但保留完整学号','方案C：删除姓名和学号，只保留匿名编号、成绩区间和题型正确率','方案D：原表直接上传，同时要求AI不要泄露'].map(x=><label className={work[2].plan===x?'picked':''} key={x}><input type="radio" checked={work[2].plan===x} onChange={()=>updateWork({plan:x})}/><span>{x}</span></label>)}</div><button className="stage-submit" disabled={!work[2].plan} onClick={submitJudge}>提交第3项独立判断</button></section>}{phase==='learn'&&<Feedback score={fscore} tags={tags} onNext={()=>setPhase('improve')} checklist={['只提供完成分析所需的最少数据','删除姓名和完整学号等直接标识','不能用一句“请勿泄露”代替脱敏','未公开企业数据和身份信息不输入公共模型']}/>} {phase==='improve'&&<section className="task-stage"><span>第三阶段 · 应用改进</span><h3>现在为真实教学选择安全的数据使用方法</h3><div className="radio-row"><label className={improved[2].choice==='只使用匿名汇总数据'?'picked':''}><input type="radio" checked={improved[2].choice==='只使用匿名汇总数据'} onChange={()=>updateImproved({...improved[2],choice:'只使用匿名汇总数据'})}/>只使用匿名汇总数据</label><label className={improved[2].choice==='继续上传原始表'?'picked':''}><input type="radio" checked={improved[2].choice==='继续上传原始表'} onChange={()=>updateImproved({...improved[2],choice:'继续上传原始表'})}/>继续上传原始表</label></div><h3>还应采取哪些处理？</h3><p><b>多选题：</b>选择所有必要的安全处理措施。</p><div className="choice-cards">{['删除姓名','删除完整学号','只保留分析所需数据','用“不要泄露”代替脱敏'].map(x=><label className={(improved[2].safeguards||[]).includes(x)?'picked':''} key={x}><input type="checkbox" checked={(improved[2].safeguards||[]).includes(x)} onChange={e=>updateImproved({...improved[2],safeguards:e.target.checked?[...(improved[2].safeguards||[]),x]:(improved[2].safeguards||[]).filter((y:string)=>y!==x)})}/>{x}</label>)}</div><button className="stage-submit" disabled={!canImprove()||saving} onClick={save}>保存第3项学习证据</button>{saveError&&<em className="save-error">{saveError}</em>}</section>}</>}
 {phase==='done'&&<section className="task-done"><span>✓ {tasks[step].name}已完成</span><h3>已形成“独立判断—方法反馈—应用改进”学习证据</h3><p>本项记录已写入本机SQLite，教师端可以查看匿名诊断并完成复核。</p>{step<2?<button onClick={next}>继续第{step+2}项：{tasks[step+1].name} →</button>:<div className="all-done"><b>{completed.every(Boolean)?'本轮三项AI使用准备已全部完成':'第3项已完成，可返回补充前面的任务'}</b></div>}</section>}
 </div>}
function Feedback({score,tags,onNext,checklist=[]}:{score:number;tags:string[];onNext:()=>void;checklist?:string[]}){return <section className="method-feedback"><span>第二阶段 · 方法反馈</span><div className="feedback-score"><b>{score}</b><small>首次判断完整度</small></div><h3>{tags.length?'这次判断还遗漏了以下要点':'首次判断已经覆盖主要要点'}</h3>{tags.length?<ul>{tags.map(x=><li key={x}>{x}</li>)}</ul>:<p>继续阅读方法清单，再把方法应用到新版本中。</p>}{checklist.length>0&&<div className="checklist"><b>本项方法清单</b>{checklist.map(x=><p key={x}>✓ {x}</p>)}</div>}<button onClick={onNext}>我已理解，进入应用改进 →</button></section>}
