'use client';
import {useEffect,useMemo,useState} from 'react';
import LiteracyLab from './LiteracyLab';
import LiteracyTeacher from './LiteracyTeacher';
import ManagementLab from './ManagementLab';
import DiagnosticAssessment from './DiagnosticAssessment';
import UnifiedDecision from './UnifiedDecision';
type Status={appA:boolean;appB:boolean};
type Panel='role'|'student'|'teacher'|'method'|'lab'|'literacyTeacher'|'trainIntro'|'assessmentIntro'|'transfer'|'about'|'guide'|null;
const LIFE='http://127.0.0.1:3000',PAYMENT='http://127.0.0.1:3001';
const majors=['财经','商贸','旅游','教育','信息技术','其他专业'];
const methods=[['结构化表达','说清目标、条件与输出'],['输出核验','区分事实、推断与建议'],['隐私保护','识别敏感数据与使用边界'],['人机协同','学生先判断，AI后辅助'],['专业迁移','把通用方法用于专业任务']];
const flow=[['明确任务','说清要解决的问题与必要条件'],['首次判断','学生先形成自己的分析'],['AI辅助','用于整理、追问和表达优化'],['核验修正','检查专业结论并说明修改依据'],['形成证据','保留首次判断与订正过程'],['教师反馈','依据过程实施教学干预']];
function serviceName(kind:'life'|'payment'){return kind==='life'?'生活经济事项辨析':'数字支付业务推演'}
export default function Home(){
 const [status,setStatus]=useState<Status>({appA:false,appB:false});const [checking,setChecking]=useState(true);const [panel,setPanel]=useState<Panel>(null);const [prepDone,setPrepDone]=useState(false);const [major,setMajor]=useState('财经');const [task,setTask]=useState('');const [goal,setGoal]=useState('');const [limits,setLimits]=useState('');
 async function check(){setChecking(true);try{const r=await fetch('/api/status',{cache:'no-store'}),d=await r.json();setStatus({appA:!!d.appA,appB:!!d.appB})}catch{}finally{setChecking(false)}}
 useEffect(()=>{check();const sync=()=>setPrepDone(localStorage.getItem('finance-ai-prep-complete')==='true');sync();window.addEventListener('finance-ai-prep-updated',sync);const id=setInterval(check,12000);return()=>{clearInterval(id);window.removeEventListener('finance-ai-prep-updated',sync)}},[]);
 function launch(kind:'life'|'payment'){const ready=kind==='life'?status.appA:status.appB;if(!ready&&!confirm(`${serviceName(kind)}当前未检测到运行。仍要尝试打开吗？\n请先运行 START-SPECIAL-SCENARIO.cmd。`))return;window.open(kind==='life'?LIFE:PAYMENT,'_blank','noopener,noreferrer')}
 const prompt=useMemo(()=>`【专业情境】${major}\n【任务】${task||'请描述需要完成的专业任务'}\n【目标】${goal||'请说明希望形成的成果'}\n【数据、规则与限制】${limits||'请补充可用信息、专业规则、隐私边界和禁止事项'}\n【输出要求】先列出信息缺口；区分事实、推断与建议；标明需要人工核验的内容；不得虚构来源。`,[major,task,goal,limits]);
 return <main className="v3">
  <header className="v3-header"><a className="brand" href="#top"><span>融</span><div><b>高职会计智能学习与教学决策平台</b><small>“辨·演·训·评·导”五环贯通 · v16.11</small></div></a><nav><a href="#tasks">实践任务</a><a href="#process">学习流程</a><a href="#teacher">教师诊断</a><button onClick={()=>setPanel('about')}>了解平台</button></nav><button className="role-top" onClick={()=>setPanel('role')}>选择身份</button></header>

  <section className="v3-hero" id="top"><div className="v3-copy"><span>人工智能＋高职会计教学应用场景</span><h1>贯通会计学习全过程<br/><em>让判断、实践与评价形成闭环</em></h1><p>平台以智能辨析为起点，通过关系推演、项目实训和过程评价形成学习证据，由人工智能辅助反馈、教师完成教学决策。</p><div className="role-actions"><button onClick={()=>setPanel('student')}>学生入口：开始学习 <i>→</i></button><button onClick={()=>setPanel('teacher')}>教师入口：查看学情</button><button className="guide-entry" onClick={()=>setPanel('guide')}>▶ 观看30秒案例导览</button></div><div className="method-strip">{methods.map(x=><span key={x[0]}>{x[0]}</span>)}<button onClick={()=>setPanel('method')}>了解方法</button></div></div><div className="demo-card"><div className="demo-head"><span>示例任务</span><i>财经专业实践</i></div><h2>花呗购买耳机并于下月还款</h2><p>不是先问AI答案，而是完成四个学习动作：</p><ol><li><b>01</b><span>先判断发生了什么</span></li><li><b>02</b><span>识别主体、资源、义务与时间</span></li><li><b>03</b><span>使用AI整理和追问</span></li><li><b>04</b><span>核验反馈并完成人工修正</span></li></ol><button onClick={()=>setPanel('student')}>学生进入任务选择 →</button></div></section>

  <section className="service-status"><div><b>本地实践服务</b><span>统一启动后可直接进入任务</span></div><button onClick={()=>launch('life')}><i className={status.appA?'on':''}/><span>生活事项智能辨析<small>{checking?'正在检测':status.appA?'可以进入':'尚未启动'}</small></span><em>进入 →</em></button><button onClick={()=>launch('payment')}><i className={status.appB?'on':''}/><span>数字支付关系推演<small>{checking?'正在检测':status.appB?'可以进入':'尚未启动'}</small></span><em>进入 →</em></button><button onClick={()=>setPanel('trainIntro')}><i className="on"/><span>管理会计项目实训<small>已集成至门户</small></span><em>进入 →</em></button><button onClick={()=>setPanel('assessmentIntro')}><i className="on"/><span>会计诊断测评<small>已集成至门户</small></span><em>进入 →</em></button><button className="status-refresh" onClick={check}>↻ 刷新</button></section>

  <section className="v3-section five-center" id="tasks"><div className="v3-title"><span>五环任务中心</span><h2>“辨·演·训·评·导”如何贯通？</h2><p>五环不是五个孤立功能，而是从问题识别、关系建模到实践评价和教学干预的循环。</p></div><div className="five-loop"><article className="ring-bian"><i>辨</i><div><span>智能辨析</span><h3>看清事项与问题</h3><p>辨析生活经济事项、主体与权利义务，检查AI回答和数据边界。</p><button onClick={()=>setPanel('student')}>进入辨析任务 →</button></div></article><b>→</b><article className="ring-yan"><i>演</i><div><span>关系推演</span><h3>把业务关系动起来</h3><p>用主体、箭头和时间轴推演数字支付中的资金、商品服务与义务。</p><button onClick={()=>launch('payment')}>进入关系推演 →</button></div></article><b>→</b><article className="ring-xun"><i>训</i><div><span>项目实训</span><h3>完成管理会计项目</h3><p>围绕预算、成本、本量利和投资决策开展项目式实训。</p><button onClick={()=>setPanel('trainIntro')}>查看实训项目 →</button></div></article><b>→</b><article className="ring-ping"><i>评</i><div><span>过程评价</span><h3>形成诊断学习证据</h3><p>结合过程记录与自编示范题，识别题型、知识点和应用改进情况。</p><button onClick={()=>setPanel('assessmentIntro')}>进入诊断测评 →</button></div></article><b>→</b><article className="ring-dao"><i>导</i><div><span>教学引导</span><h3>反馈、复核与干预</h3><p>规则提供诊断，AI辅助反馈，教师确认、退回并安排后续任务。</p><button onClick={()=>setPanel('teacher')}>进入教师决策 →</button></div></article></div><div className="course-routes"><article><b>基础会计学习路径</b><span>辨 → 演 → 评 → 导</span><p>从生活事项认知进入数字支付关系，再通过诊断测评形成教学反馈。</p></article><article><b>管理会计实训路径</b><span>辨 → 训 → 评 → 导</span><p>先明确项目条件，再完成项目实训、过程评价和教师干预。</p></article><article><b>循环改进</b><span>导 → 辨／训</span><p>教师反馈不是终点，而是下一轮辨析、推演或实训的起点。</p></article></div></section>

  <section className="v3-process" id="process"><div className="v3-title light"><span>五环共同原则</span><h2>每个任务内部都坚持“先判断，后支持”</h2><p>五环是总体场景结构，下面四步是各环节共同采用的学习方法。</p></div><div className="flow-line common-four">{[['学生先判断','先形成自己的分析，不提前查看答案'],['规则与AI后反馈','规则处理确定性问题，AI辅助追问与表达'],['学生再改进','根据反馈修改判断、关系或计算结果'],['教师最终复核','教师确认、退回并安排后续任务']].map((x,i)=><article key={x[0]}><span>0{i+1}</span><b>{x[0]}</b><p>{x[1]}</p>{i<3&&<i>→</i>}</article>)}</div></section>

  <section className="v3-teacher" id="teacher"><div><span>教师教学诊断</span><h2>不只看最终答案，<br/>更要看判断如何改变</h2><p>平台记录学生首次判断、诊断反馈和订正过程，帮助教师定位困难、安排干预并完成最终复核。</p><button onClick={()=>setPanel('teacher')}>查看教师入口 →</button></div><div className="teacher-three"><article><span>01</span><b>完成了什么</b><p>查看任务进度和学习产出</p></article><article><span>02</span><b>在哪里出错</b><p>查看错误标签和首次判断</p></article><article><span>03</span><b>怎样实施干预</b><p>比较订正轨迹并安排后续任务</p></article></div></section>

  <section className="principles"><b>平台使用原则</b>{[['先学后助','学生先判断，AI后介入'],['规则优先','确定性知识使用规则校验'],['隐私分级','支持真实、模糊和模拟信息'],['教师定评','教师保留最终评价权']].map(x=><article key={x[0]}><i>✓</i><span><b>{x[0]}</b><small>{x[1]}</small></span></article>)}<button onClick={()=>setPanel('about')}>查看详细说明</button></section>
  <footer><b>高职会计智能学习与教学决策平台</b><span>“辨·演·训·评·导”五环贯通</span><a href="#top">返回顶部 ↑</a></footer>

  {panel&&<div className="v3-modal" onClick={()=>setPanel(null)}><div className={['transfer','lab','literacyTeacher','trainIntro','assessmentIntro','teacher'].includes(panel||'')?'wide':''} onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setPanel(null)}>×</button>{panel==='role'&&<><span>请选择使用身份</span><h2>从哪个入口进入？</h2><p className="intro">学生完成学习任务，教师查看学习过程和复核结果。</p><div className="identity-cards"><button onClick={()=>setPanel('student')}><i>学</i><b>学生入口</b><p>完成AI使用准备、生活事项辨析和数字支付推演</p><em>开始学习 →</em></button><button onClick={()=>setPanel('teacher')}><i>教</i><b>教师入口</b><p>查看学习轨迹、错误类型和应用改进结果</p><em>查看学情 →</em></button></div></>}{panel==='student'&&<><span>学生实践入口</span><h2>选择今天的实践任务</h2><p className="intro">进入任务前先确认学习目标。财经实践工具需要使用学生演示账号登录。</p><div className="entry-list"><button onClick={()=>setPanel('lab')}><i>方法</i><span><b>学习前准备：正确使用AI</b><small>把问题说清楚、检查AI回答、保护学习数据</small></span><em>→</em></button><button onClick={()=>launch('life')}><i>事项</i><span><b>生活经济事项辨析</b><small>登录后选择“使用模拟事项”进入完整学习流程</small></span><em>→</em></button><button onClick={()=>launch('payment')}><i>推演</i><span><b>数字支付业务推演</b><small>登录后从“场景大厅”选择数字支付实验</small></span><em>→</em></button></div><p className="account">学生账号：student_demo　密码：demo1234</p></>}
   {panel==='teacher'&&<><span>导 · 五环统一教学决策</span><h2>从学习证据到教师干预</h2><UnifiedDecision/></>}
   {panel==='lab'&&<><span>AI通识能力实践工坊</span><h2>先判断，再反馈，再订正</h2><p className="intro">三个任务均由确定性规则进行首次诊断，核心流程不依赖在线模型。</p><LiteracyLab/></>}
   {panel==='literacyTeacher'&&<><span>正确使用AI学习诊断</span><h2>查看首次判断与订正过程</h2><LiteracyTeacher/></>}
   {panel==='method'&&<><span>学习前准备：正确使用AI</span><h2>五项能力，一套共同方法</h2><p className="intro">不同专业使用不同内容，但共同遵循先判断、再辅助、后核验的学习原则。</p><div className="method-detail">{methods.map((x,i)=><article key={x[0]}><i>0{i+1}</i><div><b>{x[0]}</b><p>{x[1]}</p></div></article>)}</div><button className="main-btn" onClick={()=>setPanel('transfer')}>用这套方法创建专业任务 →</button></>}
   {panel==='transfer'&&<><span>跨专业AI任务迁移工坊</span><h2>创建结构化专业任务</h2><p className="intro">所有输入只在当前浏览器页面处理，不保存、不上传。</p><div className="workshop-v3"><div><label>专业方向<select value={major} onChange={e=>setMajor(e.target.value)}>{majors.map(x=><option key={x}>{x}</option>)}</select></label><label>专业任务<textarea value={task} onChange={e=>setTask(e.target.value)} placeholder="描述需要完成的真实专业任务"/></label><label>预期成果<input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="说明希望形成什么成果"/></label><label>数据、规则与限制<textarea value={limits} onChange={e=>setLimits(e.target.value)} placeholder="补充专业规则、隐私边界和禁止事项"/></label></div><pre>{prompt}</pre></div><p className="privacy-note">提交给任何AI工具前，请再次检查个人信息、专业规则和最终责任主体。</p></>}
   {panel==='trainIntro'&&<><span>训 · 管理会计项目实训</span><h2>辨条件、做计算、看反馈、再改进</h2><p className="intro">四个代表性项目统一使用学生账号和本地SQLite，不向QuickForm提交姓名、班级和成绩。</p><ManagementLab/></>}
   {panel==='assessmentIntro'&&<><span>评 · 过程评价与诊断测评</span><h2>高职会计自编示范性诊断测评</h2><p className="intro">30个计分小题全部重新编写，规则评分定位题型和知识点薄弱项。</p><DiagnosticAssessment/></>}
   {panel==='guide'&&<><span>教师形象案例导览</span><h2>30秒看懂“辨·演·训·评·导”</h2><p className="intro">从真实生活事项出发，看见会计关系、学习过程与教学决策如何形成闭环。</p><div className="guide-video"><video controls playsInline preload="metadata"><source src="/videos/case-introduction-30s.mp4" type="video/mp4"/>当前浏览器不支持视频播放。</video></div><p className="guide-note">本导览基于本人授权肖像，使用智能视频技术制作，仅用于案例说明与教学导入。</p></>}
   {panel==='about'&&<><span>为什么建设这个平台</span><h2>让AI通识教育与专业学习真正连接</h2><p className="about-copy">平台面向高职学生和教师。它不是软件链接集合，也不是课程成果陈列页，而是财经专业AI伴学任务入口：学生把结构化表达、输出核验、隐私保护和人机协同用于专业任务，教师依据首次判断与订正过程实施教学干预。</p><div className="about-chain"><b>AI通识方法</b><i>→</i><b>专业任务实践</b><i>→</i><b>学习过程证据</b><i>→</i><b>教师教学决策</b></div><div className="boundary"><b>当前建设边界</b><p>财经场景是已开发程度较高的深度示范；其他专业通过统一任务框架进行迁移，不声称财经工具原样适用于所有专业。确定性知识优先使用规则校验，AI负责整理、追问、反馈和变式，教师保留最终评价权。</p></div></>}
  </div></div>}
 </main>
}
