'use client';
import {useState} from 'react';
export default function HumanAIDemo({variant}:{variant:'life'|'payment'}){
 const [open,setOpen]=useState(false),[stage,setStage]=useState(0);
 const isLife=variant==='life';
 const data=isLife?{
  caseTitle:'父母转生活费，能直接认定为“收入”吗？',studentFirst:'资产增加，收入增加，会计等式平衡。',issue:'规则确认资金流入，但“收入”判断取决于会计主体。',question:'当前分析的是学生个人生活资金，还是企业会计主体？',teacher:'请先明确观察主体，再判断是否适用企业收入定义。',studentFix:'这是个人生活资金流入，不能未经主体转换就直接认定为企业收入。',final:'学生已区分个人生活视角和企业会计主体。'
 }:{
  caseTitle:'消费者支付22元，商家收入一定是22元吗？',studentFirst:'消费者支付22元，所以商家收入是22元。',issue:'平台扣点和补贴承担方尚未明确，规则无法唯一判断。',question:'平台服务费和优惠由谁承担？商家最终结算金额是多少？',teacher:'请补充平台结算单和优惠承担方，再判断商家收入。',studentFix:'消费者实付不等于商家结算额，应扣除商家承担的服务费并区分平台补贴。',final:'学生已补充多主体结算条件并修正关系图。'
 };
 function close(){setOpen(false);setStage(0)}
 return <><section className="human-ai-highlight"><div className="hai-copy"><span>教学核心亮点 · AI可信评价</span><h2>AI发现问题，教师作出判断，学生完成成长。</h2><p>低置信度与规则冲突不会直接评分，而是进入教师复核和学生再提交闭环。</p><div className="hai-roles"><article><b>AI</b><small>结构化 · 诊断 · 追问</small></article><i>→</i><article><b>教师</b><small>复核 · 决策 · 评价</small></article><i>→</i><article><b>学生</b><small>判断 · 订正 · 迁移</small></article></div></div><div className="hai-action"><em>30秒</em><strong>体验完整复核闭环</strong><button onClick={()=>setOpen(true)}>▶ 开始亮点演示</button></div></section>{open&&<div className="hai-backdrop"><div className="hai-modal"><div className="hai-modal-head"><div><span>亮点演示 · 不修改正式数据</span><h2>人机协同复核闭环</h2></div><button onClick={close}>×</button></div><div className="hai-steps">{['发现问题','教师退回','学生订正','最终确认'].map((x,i)=><div className={stage===i?'active':stage>i?'done':''} key={x}><b>{stage>i?'✓':i+1}</b><span>{x}</span></div>)}</div><div className="hai-stage">{stage===0&&<><span className="stage-label">01 · 规则与AI发现问题</span><h3>{data.caseTitle}</h3><div className="evidence-pair"><article><b>学生首次判断</b><p>{data.studentFirst}</p></article><article className="ai-evidence"><b>规则＋DeepSeek</b><p>{data.issue}</p><em>AI置信度 0.68 · 自动进入教师复核</em></article></div><div className="ai-question">AI追问：{data.question}</div><button onClick={()=>setStage(1)}>以教师身份进入复核 →</button></>}{stage===1&&<><span className="stage-label">02 · 教师保留最终评价权</span><h3>教师复核意见</h3><div className="teacher-decision"><b>专业判断</b><p>{data.teacher}</p><textarea defaultValue={data.teacher}/></div><div className="decision-buttons"><button className="return" onClick={()=>setStage(2)}>↩ 退回学生修改</button><span className="disabled-decision">直接通过（不建议）</span></div></>}{stage===2&&<><span className="stage-label">03 · 学生根据反馈完成订正</span><h3>学生重新提交</h3><div className="student-fix"><b>学生补充说明</b><p>{data.studentFix}</p></div><div className="before-after"><span>首次：{data.studentFirst}</span><i>→</i><span>订正：{data.studentFix}</span></div><button onClick={()=>setStage(3)}>返回教师最终确认 →</button></>}{stage===3&&<><span className="stage-label">04 · 教师最终确认</span><div className="success-mark">✓</div><h3>复核闭环完成</h3><p className="final-result">{data.final}</p><div className="hai-summary"><article><b>AI</b><span>发现不确定问题</span></article><article><b>教师</b><span>作出专业判断</span></article><article><b>学生</b><span>完成认知成长</span></article></div><button onClick={close}>完成演示并返回驾驶舱</button></>}</div><div className="hai-footer">这不是AI自动评分，而是“规则＋AI＋教师”共同支持的形成性评价。</div></div></div>}</>
}
