'use client';
import {useEffect,useState} from 'react';
type Student={id:string;displayName:string;username:string;lifeTotal:number;simTotal:number;revisedRate:number;averageScore:number};
type Detail={student:Student;lifeEvents:Array<any>;simulations:Array<any>};
export default function StudentTracker({classroomId}:{classroomId:string}){
 const [students,setStudents]=useState<Student[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail|null>(null),[loading,setLoading]=useState(false);
 useEffect(()=>{if(!classroomId){setStudents([]);return}fetch(`/api/students?classroomId=${classroomId}`).then(r=>r.json()).then(d=>d.ok&&setStudents(d.students))},[classroomId]);
 async function open(id:string){setSelected(id);setLoading(true);const r=await fetch(`/api/students?classroomId=${classroomId}&studentId=${id}`),d=await r.json();if(d.ok)setDetail(d);setLoading(false)}
 return <section className="student-tracker" id="student-tracker"><div className="st-head"><div><span>真实学生数据</span><h2>学生名单与个人学习轨迹</h2><p>教师只查看脱敏摘要、学习判断和订正证据</p></div><em>{students.length}名学生</em></div><div className="st-layout"><div className="st-list"><div className="st-th"><span>学生</span><span>A记录</span><span>B推演</span><span>订正率</span><span>均分</span></div>{students.map(s=><button className={selected===s.id?'active':''} onClick={()=>open(s.id)} key={s.id}><span><i>{s.displayName.slice(-1)}</i><b>{s.displayName}</b><small>账号：{s.username}</small></span><em>{s.lifeTotal}</em><em>{s.simTotal}</em><em>{s.revisedRate}%</em><strong>{s.averageScore}</strong></button>)}</div><div className="st-detail">{loading?<div className="st-empty">正在读取学习轨迹…</div>:detail?<><div className="student-title"><div><b>{detail.student.displayName}</b><small>登录账号：{detail.student.username}</small></div><span>生活记录 {detail.lifeEvents.length}</span><span>数字推演 {detail.simulations.length}</span></div><h3>应用A · 最近生活学习卡</h3>{detail.lifeEvents.slice(0,4).map((e:any)=><article key={e.id}><span className={e.status==='REVISED'?'done':'pending'}>{e.status==='REVISED'?'已订正':'待订正'}</span><div><b>{e.analysisType}</b><p>{e.redactedSummary}</p><small>首次理由：{e.firstReason}</small>{e.revisedReason&&<small className="revision">订正：{e.revisedReason}</small>}</div><strong>{e.score}</strong></article>)}<h3>应用B · 最近数字推演</h3>{detail.simulations.slice(0,4).map((e:any)=><article key={e.id}><span className={e.status==='REVISED'?'done':'pending'}>{e.status==='REVISED'?'已订正':'待订正'}</span><div><b>{e.scenarioTitle} · 时点{e.stepIndex+1}</b><p>{e.firstChoice}</p><small>理由：{e.firstReason}</small></div><strong>{e.score}</strong></article>)}</>:<div className="st-empty"><b>选择一名学生</b><p>查看“首次判断—反馈—订正—迁移”的学习证据。</p></div>}</div></div></section>
}
