'use client';
import {useEffect,useState} from 'react';
type Room={id:string;name:string;term:string;inviteCode:string;memberRole:string;course:{name:string};cycles:Array<{id:string;name:string;stage:number;startsAt:string;endsAt:string}>;_count:{members:number}};
export default function ClassroomManager({onSelect}:{onSelect?:(id:string)=>void}){
 const [rooms,setRooms]=useState<Room[]>([]),[name,setName]=useState(''),[term,setTerm]=useState('2026学年'),[message,setMessage]=useState(''),[active,setActive]=useState<string|null>(null),[cycleName,setCycleName]=useState('阶段一：看见经济活动'),[stage,setStage]=useState('1'),[startsAt,setStartsAt]=useState(new Date().toISOString().slice(0,10)),[endsAt,setEndsAt]=useState(new Date(Date.now()+7*86400000).toISOString().slice(0,10)),[suggested,setSuggested]=useState('3'),[maxScored,setMaxScored]=useState('5');
 async function load(){const r=await fetch('/api/classrooms',{cache:'no-store'});const d=await r.json();if(d.ok){setRooms(d.classrooms);if(!active&&d.classrooms[0]){setActive(d.classrooms[0].id);onSelect?.(d.classrooms[0].id)}}}
 useEffect(()=>{load()},[]);
 async function createRoom(){if(!name.trim())return;const r=await fetch('/api/classrooms',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,term,courseName:'基础会计'})});const d=await r.json();setMessage(d.ok?`已创建班级，邀请码：${d.classroom.inviteCode}`:d.error);if(d.ok){setName('');load()}}
 async function createCycle(){if(!active)return;const r=await fetch('/api/cycles',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({classroomId:active,name:cycleName,stage,startsAt,endsAt,suggestedCount:suggested,maxScoredCount:maxScored})});const d=await r.json();setMessage(d.ok?'学习周期已创建':d.error);if(d.ok)load()}
 return <section className="class-manager" id="classroom-manager"><div className="cm-head"><div><span>真实班级管理</span><h2>课程、邀请码与学习周期</h2><p>学生使用邀请码注册后自动加入班级</p></div>{message&&<em>{message}</em>}</div><div className="cm-grid"><div className="room-list">{rooms.map(r=><button className={active===r.id?'active':''} onClick={()=>{setActive(r.id);onSelect?.(r.id)}} key={r.id}><div><b>{r.name}</b><small>{r.course.name} · {r.term}</small></div><span>{r._count.members}人</span><code>{r.inviteCode}</code><i>{r.cycles[0]?.name||'暂无周期'}</i></button>)}</div><div className="cm-actions"><article><b>新建教学班</b><input value={name} onChange={e=>setName(e.target.value)} placeholder="例如：财富2509"/><input value={term} onChange={e=>setTerm(e.target.value)} placeholder="学期"/><button onClick={createRoom}>创建并生成邀请码</button></article><article><b>为选中班级创建周期</b><input value={cycleName} onChange={e=>setCycleName(e.target.value)} placeholder="周期名称"/><select value={stage} onChange={e=>setStage(e.target.value)}><option value="1">阶段一 · 看见经济活动</option><option value="2">阶段二 · 会计要素与等式</option><option value="3">阶段三 · 主体与确认基础</option><option value="4">阶段四 · 企业会计迁移</option></select><div className="cycle-dates"><label>开始<input type="date" value={startsAt} onChange={e=>setStartsAt(e.target.value)}/></label><label>截止<input type="date" value={endsAt} onChange={e=>setEndsAt(e.target.value)}/></label></div><div className="cycle-counts"><label>建议完成<input type="number" min="1" value={suggested} onChange={e=>setSuggested(e.target.value)}/></label><label>最多计分<input type="number" min="1" value={maxScored} onChange={e=>setMaxScored(e.target.value)}/></label></div><button onClick={createCycle} disabled={!active}>创建学习周期</button></article></div></div></section>
}
