'use client';
import {useState} from 'react';
type Props={type:string;summary:string;amount:string};
const configs:Record<string,{nodes:string[];flows:Array<[number,number,string,string]>;migration:string}>={
 '账户转换':{nodes:['银行卡','校园卡','实际消费'],flows:[[0,1,'资金账户转换','money'],[1,2,'后续消费','service']],migration:'企业类比：一个资产账户减少，另一个资产账户增加；实际消费发生时再分析费用。'},
 '延期支付':{nodes:['商家','学生','信用支付'],flows:[[0,1,'商品或服务','service'],[1,2,'偿还义务','duty']],migration:'企业类比：取得资源并形成现时义务，资产和负债可能同时增加。'},
 '垫付与收回':{nodes:['学生','商家','共同参与者'],flows:[[0,1,'先行支付','money'],[2,0,'未来归还','right']],migration:'企业类比：货币资金减少，同时形成收回权利，属于资产内部变化。'},
 '借出款项':{nodes:['学生','借款人','未来收回'],flows:[[0,1,'资金借出','money'],[1,2,'收回权利','right']],migration:'资金流出不等于费用；符合条件时形成对他人的收回权利。'},
 '退货与退款':{nodes:['学生','商家','待退款'],flows:[[1,2,'确认退款','right'],[2,0,'退款到账','money']],migration:'退款通常是原交易冲回，不是新的收入；确认与到账可能处于不同时点。'},
 '家庭资金转入':{nodes:['家庭','学生账户','企业类比'],flows:[[0,1,'家庭转入','money'],[1,2,'先明确主体','subject']],migration:'个人资金流入不能不加转换地直接认定为企业收入。'}
};
export default function LifeEventModel({type,summary,amount}:Props){const [open,setOpen]=useState(false),[layer,setLayer]=useState('全部');const c=configs[type]||{nodes:['事项主体','资金或资源','企业会计'],flows:[[0,1,'经济关系','money'],[1,2,'迁移分析','subject']] as Array<[number,number,string,string]>,migration:'需结合主体、业务性质、凭证和时间节点进一步判断。'};return <><button className="open-life-model" onClick={()=>setOpen(true)}>◉ 查看这笔事项的动态认知模型</button>{open&&<div className="life-model-backdrop" onClick={()=>setOpen(false)}><div className="life-model-modal" onClick={e=>e.stopPropagation()}><header><div><span>知识模型化</span><h2>一笔生活事项的四层认知模型</h2><p>{summary} · {amount}</p></div><button onClick={()=>setOpen(false)}>×</button></header><nav>{['全部','主体','资金/资源','权利义务','企业迁移'].map(x=><button className={layer===x?'active':''} onClick={()=>setLayer(x)} key={x}>{x}</button>)}</nav><div className="life-model-canvas"><svg viewBox="0 0 900 360"><defs><marker id="lm-arrow" markerWidth="9" markerHeight="9" refX="8" refY="3" orient="auto"><path d="M0,0 L0,6 L9,3 z" fill="#6876df"/></marker></defs>{c.flows.map((f,i)=>{const x1=150+i*300+85,x2=150+(i+1)*300-85,y=175;const visible=layer==='全部'||layer==='资金/资源'&&['money','service'].includes(f[3])||layer==='权利义务'&&['right','duty'].includes(f[3])||layer==='主体'&&f[3]==='subject';return visible&&<g key={i}><line className={`model-flow ${f[3]}`} x1={x1} y1={y} x2={x2} y2={y} markerEnd="url(#lm-arrow)"/><rect x={(x1+x2)/2-65} y={y-35} width="130" height="26" rx="13"/><text x={(x1+x2)/2} y={y-18} textAnchor="middle">{f[2]}</text></g>})}{c.nodes.map((n,i)=><g className="model-node" key={n}><circle cx={150+i*300} cy="175" r="70"/><circle className="inner" cx={150+i*300} cy="175" r="54"/><text x={150+i*300} y="181" textAnchor="middle">{n}</text></g>)}</svg><div className="model-layer-cards"><article><b>生活语言</b><p>{summary}</p></article><i>→</i><article><b>经济实质</b><p>{type}</p></article><i>→</i><article className="migration"><b>企业会计迁移</b><p>{c.migration}</p></article></div></div><div className="model-explain"><b>如何使用模型</b><span>先看主体</span><i>→</i><span>再看资金或资源</span><i>→</i><span>识别权利义务</span><i>→</i><span>最后迁移到企业会计</span></div></div></div>}</>}
