'use client';
import {useState} from 'react';
type User={id:string;username:string;displayName:string;role:string};
export default function LoginScreen({appName,onLogin}:{appName:string;onLogin:(u:User)=>void}){
 const [username,setUsername]=useState('student_demo'),[password,setPassword]=useState('demo1234'),[displayName,setDisplayName]=useState(''),[inviteCode,setInviteCode]=useState(''),[registering,setRegistering]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 async function loginWith(u:string,p:string){setLoading(true);setError('');try{const r=await fetch('/api/auth',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username:u,password:p})});const d=await r.json();if(d.ok)onLogin(d.user);else setError(d.error||'登录失败')}catch{setError('无法连接本机服务')}finally{setLoading(false)}}
 async function submit(){return loginWith(username,password)}
 async function register(){setLoading(true);setError('');setMessage('');try{const r=await fetch('/api/register',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({username,password,displayName,inviteCode})});const d=await r.json();if(d.ok){setMessage(`注册成功，已加入“${d.classroom}”，请登录`);setRegistering(false)}else setError(d.error)}catch{setError('注册失败')}finally{setLoading(false)}}
 return <main className="login-page"><section className="login-brand"><span>AI × 会计教学</span><h1>{appName}</h1><p>生活情境进入 · 人机协同诊断 · 过程性评价</p><div><article><b>01</b><span>学生独立判断</span></article><article><b>02</b><span>规则与AI追问</span></article><article><b>03</b><span>教师最终复核</span></article></div></section><section className="login-card"><div className="login-logo">∑</div><span className="login-kicker">{registering?'使用邀请码加入班级':'演示账号登录'}</span><h2>{registering?'注册学生账号':'进入教学空间'}</h2>{registering&&<label>姓名或昵称<input value={displayName} onChange={e=>setDisplayName(e.target.value)} placeholder="用于教师识别"/></label>}<label>用户名<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="4—24位字母、数字或下划线"/></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!registering&&submit()} placeholder="至少6位"/></label>{registering&&<label>班级邀请码<input value={inviteCode} onChange={e=>setInviteCode(e.target.value.toUpperCase())} placeholder="例如 DEMO2026"/></label>}{error&&<p className="login-error">{error}</p>}{message&&<p className="login-success">{message}</p>}<button className="login-submit" onClick={registering?register:submit} disabled={loading}>{loading?'正在处理…':registering?'注册并加入班级':'登录'}</button><button className="mode-switch" onClick={()=>{setRegistering(!registering);setError('');setMessage('')}}>{registering?'已有账号，返回登录':'没有账号？使用邀请码注册'}</button>{!registering&&<><div className="demo-accounts"><button onClick={()=>loginWith('student_demo','demo1234')}><b>一键进入学生演示</b><span>账号：student_demo</span></button><button onClick={()=>loginWith('teacher_demo','demo1234')}><b>一键进入教师演示</b><span>账号：teacher_demo</span></button></div><small>演示密码均为 demo1234 · 会话保存在HttpOnly Cookie</small></>}</section></main>
}
