'use client';
import {useEffect,useState} from 'react';
type Student={id:string;displayName:string;username:string};type Credential={id:string;displayName:string;username:string;password:string};
export default function StudentAccountManager({classroomId}:{classroomId:string}){
 const [students,setStudents]=useState<Student[]>([]),[names,setNames]=useState(''),[credentials,setCredentials]=useState<Credential[]>([]),[message,setMessage]=useState('');
 async function load(){if(!classroomId)return;const r=await fetch(`/api/students?classroomId=${classroomId}`),d=await r.json();if(d.ok)setStudents(d.students)}
 useEffect(()=>{load();setCredentials([])},[classroomId]);
 async function create(){const list=names.split(/\r?\n|,|，/).map(x=>x.trim()).filter(Boolean);if(!list.length)return;const r=await fetch('/api/students',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({classroomId,names:list})}),d=await r.json();if(d.ok){setCredentials(d.credentials);setNames('');setMessage(`已创建${d.credentials.length}个学生账号，请立即下载或复制临时密码。`);load()}else setMessage(d.error)}
 async function reset(student:Student){if(!confirm(`确定重置“${student.displayName}”的密码吗？`))return;const r=await fetch('/api/students',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({classroomId,studentId:student.id})}),d=await r.json();if(d.ok){setCredentials([{...student,password:d.password}]);setMessage('临时密码已重置，仅本次显示。')}else setMessage(d.error)}
 function download(){const rows=[['姓名','用户名','临时密码'],...credentials.map(x=>[x.displayName,x.username,x.password])],csv='\uFEFF'+rows.map(r=>r.map(v=>`"${v}"`).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download='学生临时账号清单.csv';a.click();URL.revokeObjectURL(a.href)}
 if(!classroomId)return null;
 return <section className="account-manager" id="account-manager"><div className="am-head"><div><span>账号开通</span><h2>教师创建学生试用账号</h2><p>每行输入一名学生，系统自动生成用户名与一次性临时密码</p></div><em>{students.length}个账号</em></div><div className="am-grid"><div><label>学生姓名或试用名称（每行一个）</label><textarea value={names} onChange={e=>setNames(e.target.value)} placeholder={'评委试用学生\n张三\n李四'}/><button onClick={create}>批量生成账号</button></div><div className="account-list"><b>当前班级账号</b>{students.slice(0,8).map(s=><div key={s.id}><span><strong>{s.displayName}</strong><small>账号：{s.username}</small></span><button onClick={()=>reset(s)}>重置密码</button></div>)}{students.length>8&&<small>另有{students.length-8}名学生，请在下方学生名单查看。</small>}</div></div>{message&&<p className="am-message">{message}</p>}{credentials.length>0&&<div className="credential-box"><div><b>临时账号凭据</b><span>密码只在本次生成后显示，请立即下载。</span><button onClick={download}>下载CSV</button></div><table><thead><tr><th>姓名</th><th>用户名</th><th>临时密码</th></tr></thead><tbody>{credentials.map(c=><tr key={c.id}><td>{c.displayName}</td><td>{c.username}</td><td><code>{c.password}</code></td></tr>)}</tbody></table></div>}</section>
}
